### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by lukas-frystak-sonarsource**

### CODE REVIEW

**Comment by lukas-frystak-sonarsource** [comment]
This is a comment with a badge
[Code Smells](https://lukf.eu.ngrok.io/dashboard?id=last_analysis_date_test)

**Comment by lfrystak** [comment]
This is a comment from a third party
[Technical Debt](https://lukf.eu.ngrok.io/dashboard?id=last_analysis_date_test)

**Comment by lfrystak** [comment]
Hello
[Maintainability Rating](https://lukf.eu.ngrok.io/dashboard?id=last_analysis_date_test)

**Comment by lfrystak** [comment]
http://localhost:19900/api/project_badges/measure?project=last_analysis_date_test&metric=alert_status&token=sqb_e457e056ae9da654d74f1117e8a5b93602b99597

**Pull request closed without merging**
